name: sf_env
channels:
  - snowflake
dependencies:
  - streamlit
  - snowflake-snowpark-python
  - python-docx
  - snowflake
  - snowflake-ml-python
  - snowflake.core
  - st-theme
  - streamlit-extras
  - pandas
